// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzgqazpjuiatvnroiyqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6Z3FhenBqdWlhdHZucm9peXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTE0MTEsImV4cCI6MjA1MzEyNzQxMX0.JCrWjipmN7_tW0rKjY-7Z1R-A6eacLwR3dIOFaCbI4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});